#!/bin/bash

# Description: Link dotfiles to home directory with Chezmoi

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:enjunior-git/dotfiles.git 
fi

exit 0
