#!/bin/bash

# Description: Link dotfiles to home directory with Chezmoi

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/enjunior-git/dotfiles.git
fi

curl -sS https://starship.rs/install.sh | sh -s -- --yes

exit 0
