-- Generated by nwg-displays on 2026-08-08 at 06:24:58. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1863x1080",
    scale = 1.5
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1080@120.0",
    position = "1280x0",
    scale = 1.0
})
