
[[window]]
name = "terminal"
startup_script = "ls"

[[session]]
name = "Home"
path = "~"
startup_command = "ls"

[[session]]
name="Dev"
path="~/dev"
startup_command="ls"

[[session]]
name="Chip 8 | Zig"
path="~/dev/chip-8-zig/"
startup_command="nvim ."

[[session]]
name="Media save"
path="~/dev/media-save/"
startup_command="nvim ."
windows=["terminal"]

[[session]]
name="Workout Chatbot"
path="~/dev/workout/"
startup_command="nvim ."
windows=["terminal"]

[[session]]
name="setup"
path="~/dev/setup/"
startup_command="nvim ."

[[session]]
name="sesh ulauncher"
path="~/dev/sesh-ulauncher/"
startup_command="nvim ."

[[session]]
name="wcard"
path="~/dev/wcard"
startup_command="nvim ."

[[session]]
name="tmux config"
path="~/.config/tmux"
startup_command="nvim tmux.conf"

[[session]]
name="sesh config"
path="~/.config/sesh"
startup_command="nvim sesh.toml"
